// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPybtht28Ac3fxVZWZfp0RVn-aSvWvxkc',
    appId: '1:1001795053415:web:ef349f1a9fc3423ed771c2',
    messagingSenderId: '1001795053415',
    projectId: 'appplantinha',
    authDomain: 'appplantinha.firebaseapp.com',
    storageBucket: 'appplantinha.firebasestorage.app',
    measurementId: 'G-VQB7Y30KZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgDcrK1YDRVYqsuYlfsnujdGzqgqQvkIs',
    appId: '1:1001795053415:android:925fcb3ee97f229bd771c2',
    messagingSenderId: '1001795053415',
    projectId: 'appplantinha',
    storageBucket: 'appplantinha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRYTXadht5CD5dKUc1QkkvJNDFy8ifNII',
    appId: '1:1001795053415:ios:4dcfb65289b17cb4d771c2',
    messagingSenderId: '1001795053415',
    projectId: 'appplantinha',
    storageBucket: 'appplantinha.firebasestorage.app',
    iosBundleId: 'com.example.appPlantinha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRYTXadht5CD5dKUc1QkkvJNDFy8ifNII',
    appId: '1:1001795053415:ios:4dcfb65289b17cb4d771c2',
    messagingSenderId: '1001795053415',
    projectId: 'appplantinha',
    storageBucket: 'appplantinha.firebasestorage.app',
    iosBundleId: 'com.example.appPlantinha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPybtht28Ac3fxVZWZfp0RVn-aSvWvxkc',
    appId: '1:1001795053415:web:39b340d872a202d3d771c2',
    messagingSenderId: '1001795053415',
    projectId: 'appplantinha',
    authDomain: 'appplantinha.firebaseapp.com',
    storageBucket: 'appplantinha.firebasestorage.app',
    measurementId: 'G-BXFEK9EV48',
  );
}
